Added Tele2 API
phpservermon/phpservermon pull request #1130
Opened 2021-06-15 09:19 UTC by scheibling

Added an SMS API provider for api.tele2messaging.com (infobip-based)

2021-06-20 13:30 UTC, TimZ99 requested changes
Thank you for your time! Looks good, please add Tele2 to the README.rst.

2021-06-20 13:30 UTC, TimZ99 commented on src/psm/Txtmsg/Tele2.php
> +        else {
Why would we define the error if the request was successful? Shouldn't it be set next to the `$success = 0;`?

2021-06-20 13:30 UTC, TimZ99 commented on src/psm/Txtmsg/Tele2.php
> +         * To Do: Add validation/formatting for message to format [countrycode][number_without_0] e.g. 4571234567 instead of +451234567/00451234567/01234567
Could this be added before merging?

2021-06-20 13:35 UTC, scheibling commented on src/psm/Txtmsg/Tele2.php
> +         * To Do: Add validation/formatting for message to format [countrycode][number_without_0] e.g. 4571234567 instead of +451234567/00451234567/01234567
No problem, I'll add it in a bit. Just have to make some finishing touches. 

I might add this verification to the Infobip API as well later on, as far as I know they have the same requirements since Tele2 is based on this API.

2021-06-20 13:40 UTC, scheibling commented on src/psm/Txtmsg/Tele2.php
> +        else {
Yep, you're right, this doesn't make any sense at all. Got a bit late when I was working on this last time.

2021-06-20 14:33 UTC, scheibling commented
Well... I seem to have screwed up my commits a bit, mixing up this PR with another one I'm planning.... 

0c7ea7c and c896eeb (Tele2.php, Readme.rst, functions.inc.php) are the only ones that belong to this PR. Could you selectively merge them, or do you want me to open an new PR?

2021-06-20 14:33 UTC, scheibling commented on src/psm/Txtmsg/Tele2.php
> +        else {
Fixed

2021-06-20 14:34 UTC, scheibling commented on src/psm/Txtmsg/Tele2.php
> +         * To Do: Add validation/formatting for message to format [countrycode][number_without_0] e.g. 4571234567 instead of +451234567/00451234567/01234567
Done, added function for formatting/verifying phone numbers

2021-06-21 20:47 UTC, TimZ99 approved these changes

2021-06-21 20:48 UTC, TimZ99 commented
Fixed it. Thank you for your time!

2021-06-21 20:49 UTC, merged

2021-06-21 22:19 UTC, scheibling commented
Sorry about the mixup, thanks for a great project! I'll be adding more PRs in the future 😃