Add Pushbullet service =)
phpservermon/phpservermon pull request #355
Opened 2016-09-12 23:10 UTC by MyTheValentinus

After long night !
I have added Pushbullet service ! 💃

2016-11-17 18:08 UTC, tperalta82 commented
+1 on this one!  , I think all add it to my production env after testing it

2016-11-17 18:12 UTC, MyTheValentinus commented
Hello @tperalta82
I'm using my version in production and work perfectly, i have just forget log listing in interface but is in database.

2017-01-13 08:11 UTC, sadortun commented
@tperalta82  can you confirm if this PR is working properly ?

@MyTheValentinus can you rebase it ? Or resolve the conflicts ? 

Thanks!

2017-01-18 16:52 UTC, MyTheValentinus commented
Hello @sadortun it's good

2017-10-22 20:56 UTC, hiagodotme commented
Show! 👍 
I've added notifications by telegram too, pull request (#527)

2018-03-07 17:18 UTC, TimZ99 requested changes
Super quick review. Had no time for testing, will do this on another moment.

2018-03-07 17:18 UTC, TimZ99 commented on src/psm/Util/Install/Installer.php
> +            $this->upgrade320();
Typo

2018-03-07 17:18 UTC, TimZ99 commented on static/css/style.css
> +	background-position: -240px -120px;
You're trying to load an icon that isn't there.

2020-01-14 18:27 UTC, closed without merging