update status.cron.php with added allowed IP check. Issue #215
phpservermon/phpservermon pull request #358
Opened 2016-09-20 11:42 UTC by pieter-groeneweg

#215 To allow scheduled status updates over the web the commandline check is extended with a check on allowed IP address(es).

In config.php add following line:

define('PSM_CRON_ALLOW', array("xxx.xxx.xxx.xxx", "yyy.yyy.yyy.yyy"))

Where the xxx's and yyy's represent the IP addresses of course

2016-09-20 13:35 UTC, sadortun commented on cron/status.cron.php
> +		header('HTTP/1.0 404 Not Found');
Please use 401 Forbidden,  instead of 404.

2016-09-20 13:35 UTC, sadortun commented on cron/status.cron.php
> +		die('<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL /cron/status.cron.php was not found on this server
Please keep the same errorsor message.

2016-09-20 13:36 UTC, sadortun requested changes
Thanks, here is a few suggestions.

2016-09-20 15:02 UTC, pieter-groeneweg commented on cron/status.cron.php
> +		die('<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL /cron/status.cron.php was not found on this server
The error message would not make sense on 401 (unauthorized, 403 is forbidden).
Reason to use 404 is that I don't need anyone trying to use some brute force attempts later on that url... a 401 implies there is something... likewise 403.

security by obfuscation sometimes does work better... ;)

2017-01-13 08:04 UTC, merged

2017-01-13 08:05 UTC, sadortun commented
Thanks, simple and effective !

2018-06-29 17:44 UTC, TimZ99 commented
@stefan-muc I agree and I changed it to 403. 
@Petrusvb The function checks if your IP is in the array. It only allows the specific IP addresses defined in the config file.