Add Pushsafer.com notification service
phpservermon/phpservermon pull request #441
Opened 2017-04-07 08:11 UTC by appzer

![Pushsafer](https://www.pushsafer.com/de/assets/logos/logo.png)
**Add pushsafer.com notification service**
> tested in live environment
> send notifications to iOS, Android or Windows 10 devices with chart image (last 20 uptime records)

Example Screenshots:
**iOS**
![Pushsafer](https://www.pushsafer.com/de/assets/examples/phpservermonitor_pushsafer_ios_1.jpg)
![Pushsafer](https://www.pushsafer.com/de/assets/examples/phpservermonitor_pushsafer_ios_2.jpg)
**Android**
![Pushsafer](https://www.pushsafer.com/de/assets/examples/phpservermonitor_pushsafer_android.jpg)
**WIN 10 Phone**
![Pushsafer](https://www.pushsafer.com/de/assets/examples/phpservermonitor_pushsafer_windows_10_phone.jpg)
**WIN 10 Desktop**
![Pushsafer](https://www.pushsafer.com/de/assets/examples/phpservermonitor_pushsafer_windows_10_desktop.jpg)
**Client Apps**
![Pushsafer](https://www.pushsafer.com/de/assets/examples/phpservermonitor_pushsafer_client.jpg)

2017-04-16 11:10 UTC, naqirizvi commented
Also looking for some integration with OneSignal.com

2017-04-18 11:06 UTC, appzer commented
i fixed the issues

2017-05-21 13:37 UTC, appzer commented
How long it takes to review the pr

2017-05-21 17:07 UTC, sadortun commented
@appzer sorry for the delay,  we did not had time yet to review and test your PR

2017-05-27 15:33 UTC, appzer commented
hi, where the problem is? In my development environment, all works fine.

Kevin

2017-08-18 22:35 UTC, TimZ99 commented
Are the `$#39;` you see around the server name in the IOS screenshot also in this version, if yes please fix, if no ignore this message 😉.

2017-08-18 22:40 UTC, TimZ99 requested changes
On a fresh install non of the server and profile settings will save. 
Saving config tab works fine. Don't know why.

When I add a server and add the Pushsafer key, manually via the database, I get a Fatal error when updating (via navigation menu). 

Not ready for production, this version isn't working for me.

2017-08-18 22:40 UTC, TimZ99 commented on src/psm/Module/Config/Controller/ConfigController.php
> +		'pushsafer_icon_on',
Is it really necessary to have _on and _off? 
Can't this be 1 variable?

2017-08-18 22:40 UTC, TimZ99 commented on src/psm/Util/Server/Updater/StatusNotifier.php
> +	protected function PushsaferChart($values) {
Maybe move this function to functions.inc.php?

2017-08-18 22:40 UTC, TimZ99 commented on src/psm/Util/Install/Installer.php
> +					('pushsafer_status', '0'),
Same as src/psm/Module/Config/Controller/ConfigController.php, why _on and _off, why not one variable?

2017-08-18 22:40 UTC, TimZ99 commented on src/templates/default/module/config/config.tpl.html
> +                    <input type="text" id="pushsafer_vibration_on" name="pushsafer_vibration_on" value="{{ pushsafer_vibration_on }}" maxlength="3" />
What does an input look like? yes/no, true/false, a number or ... ? 
Please use a placeholder or add some text.

2017-08-18 22:40 UTC, TimZ99 commented on src/templates/default/module/server/server/list.tpl.html
> +			<td class="tight hidden-phone"><div class="table-cell-title"><i class="{{ server.active_icon }}" title="{{ server.active_title }}"></i> <i class="{{ server.email_icon }}" title="{{ label_email }}"
`title="Pushsafer"` must be `title="{{ label_pushsafer }}"` to be inline with the rest.
Same for `title="Pushsafer"` must be `title="{{ label_pushover }}"`

2017-08-18 22:40 UTC, TimZ99 commented on static/css/style.css
> -/** Rtl language Style */
Why is the Rtl language part gone?

2017-08-18 22:40 UTC, TimZ99 commented on src/psm/Util/Server/Updater/StatusNotifier.php
> +				$this->addMessage(psm_get_lang('config', 'pushsafer_error_nokey'), 'error');
When the server is offline and you click update you get: `Fatal error: Call to undefined method psm\Util\Server\Updater\StatusNotifier::addMessage() in /src/psm/Util/Server/Updater/StatusNotifier.php on line 408`

2018-02-25 00:34 UTC, TimZ99 commented
Hi, I know it's a long time ago you made the PR, but I'm currently reviewing the open PR's and it seams that this one is not ready to be merged. Could you please check the review and fix the conflicts. :smile:

2020-01-14 18:46 UTC, closed without merging