SSL Certificate checking
phpservermon/phpservermon pull request #494
Opened 2017-08-01 08:12 UTC by av2k

Hello,

this is the code we use since about 9 months for certificate checking.

It adds a new column in the database to store the minimum days of remaining certificate validity and uses OpenSSL to get the server certificate details.

2017-11-01 13:56 UTC, jimwebb commented
This patch worked well for me, with two small issues:

- I believe it performs the SSL certificate check for all domains, even HTTP ones (which will fail)
- Phpservermon has a related issue in which ports can't be changed after a server is entered (https://github.com/phpservermon/phpservermon/issues/418). Normally this isn't a problem and the server monitor works fine if the port is inaccurate, but this patch needs those ports to be accurate.

(Also, if someone is here trying to implement this for themselves, you'll need to modify the "servers" database table with two new fields for this patch to work, as described in the code of this PR; they don't automatically get created and the list of servers will "disappear" without an error message if those tables don't exist.)

Thanks for doing this!

2018-03-13 16:07 UTC, TimZ99 commented
The monitor marks the websites as offline when the SSL certificate is still valid, but just under the number of days, you specify. I would say that a warning is enough. Making the box yellow instead of red and still monitoring the latency could be a good solution.

2018-04-22 21:18 UTC, TimZ99 requested changes

2018-04-22 21:18 UTC, TimZ99 commented on src/includes/functions.inc.php
> +function psm_cert_info_get($href, $port) {
Feedback in the conversation.

2018-09-12 10:50 UTC, DominikWA commented
Is it foreseeable when this will become part of the phpservermonitor? A web page without a valid certificate will appear to users as if it were unreachable, so the server monitor should report it.

2018-09-12 10:53 UTC, TimZ99 commented
@DominikWA  I think I will put it in v3.5.

2020-02-04 15:18 UTC, closed without merging