Add GatewayAPI
phpservermon/phpservermon pull request #593
Opened 2018-05-28 13:34 UTC by wardpieters

#585, #588

2018-05-28 14:26 UTC, TimZ99 requested changes

2018-05-28 14:26 UTC, TimZ99 commented on src/psm/Txtmsg/Mosms.php
> +			$result = file_get_contents($API_URL . "?username=" . $this->username . "&password=" . $this->password . "&customsender=" . $this->originator . "nr=" . $phone . "&type=text&data=" . $message);
Could you rewrite this to cURL.

2018-05-28 14:26 UTC, TimZ99 commented on src/psm/Txtmsg/Smsglobal.php
>  class Smsglobal extends Core {
Please add a list of variables that are used.

2018-05-28 14:26 UTC, TimZ99 commented on src/psm/Txtmsg/Smsglobal.php
>  		$returnedData = file_get_contents($url);
Use cURL.

2018-05-28 14:26 UTC, TimZ99 commented on src/psm/Txtmsg/Smsit.php
> +			$result = file_get_contents($URL);
cURL

2018-05-28 14:26 UTC, TimZ99 commented on src/psm/Txtmsg/Smsit.php
> +			$URL = $API_URL."?apiKey=" . $this->username . "&mobile=" . $phone . "&message=" . urlencode($message) . "&senderId=" . $urlencode(substr($this->originator,0,11));
Api key needs to use the password field.

2018-05-28 14:26 UTC, TimZ99 commented on src/psm/Txtmsg/Smsit.php
>  class Smsit extends Core {
provide a list of used variables.

2018-05-28 14:28 UTC, wardpieters commented
I screwed a bit up on ... basically everyting
But will make the changes 👍

2018-05-28 14:33 UTC, TimZ99 commented
Haha, that's not true!
File_get_content does the job, but I simply prefer cURL and want that all gateways are the same.
The same goes for using the password field instead of the username field.

I really appreciate the work you're doing for the project!

2018-05-28 14:39 UTC, TimZ99 commented on src/psm/Txtmsg/Smsit.php
> +			$URL = $API_URL."?apiKey=" . $this->username . "&mobile=" . $phone . "&message=" . urlencode($message) . "&senderId=" . $urlencode(substr($this->originator,0,11));
Fixed

2018-05-28 14:49 UTC, wardpieters commented on src/psm/Txtmsg/Mosms.php
> +			$result = file_get_contents($API_URL . "?username=" . $this->username . "&password=" . $this->password . "&customsender=" . $this->originator . "nr=" . $phone . "&type=text&data=" . $message);
Done

2018-05-28 14:56 UTC, TimZ99 commented
I can't create an account on Smsit.dk. Do you have the same problem?

2018-05-28 15:01 UTC, wardpieters commented
Yes

> Creating new users is temporarily interrupted. Send an email to info@smsit.dk for creation

2018-05-28 15:03 UTC, TimZ99 commented
Annoying! I updated the Smsit gateway to v2 and updated the error check. Only need to update it to cURL.

2018-05-28 15:03 UTC, TimZ99 commented
Which file are you working on right now?

2018-05-28 15:07 UTC, wardpieters commented
Nothing.. the power went down :joy:

2018-05-28 15:12 UTC, TimZ99 commented
Nice 😂

2018-05-28 15:39 UTC, wardpieters commented
Currently working on a few, will commit when done

2018-05-28 16:40 UTC, wardpieters commented
Please take a look if what i've done is what you want, then i will do them all :)

2018-05-28 16:41 UTC, wardpieters commented
I have my doubts about Inetworx, but just let me know if it's correct.

2018-05-28 17:05 UTC, TimZ99 commented
A sample file would be a great idea!

2018-05-28 17:53 UTC, wardpieters commented
Don't know what happend there, but what do you think of the Gateways ?

2018-05-28 17:55 UTC, TimZ99 commented
I'm testing them right now!

2018-05-28 18:03 UTC, TimZ99 commented
FreeMobileSMS is weird. There is no input for the phone number, so I guess that it will only send an SMS to the account owner. 
If I just throw the URL into my browser, it gives me a warning that https isn't supported.
Also, the URL send me to a 404-like page.

2018-05-28 18:05 UTC, wardpieters commented
It's okay, if you put in all the variables you get 403 (https://smsapi.free-mobile.fr/sendmsg?user=d&pass=d&msg=d).

I couldn't find anything online about this API, but i bet you're right about the SMS to the owner.

2018-05-28 18:05 UTC, TimZ99 commented
Think that the best option is to deprecate FreeMobileSMS as a gateway, what do you think?

2018-05-28 18:06 UTC, TimZ99 commented
Owh I didn't see the 403

2018-05-28 18:28 UTC, TimZ99 commented
Checked:

- [x] FreeMobileSMS
- [x] GatewayAPI
- [ ] Nexmo
- [ ] FreeVoipDeal
- [ ] Inetworx
- [ ] Mosms
- [ ] Octopush
- [ ] SMSGlobal
- [ ] Smsit

2018-05-28 18:39 UTC, wardpieters commented
Can i contact you on Telegram, Discord or something like that?

2018-05-28 18:47 UTC, TimZ99 commented
https://t.me/TimZ99

2018-05-28 20:27 UTC, wardpieters commented
Smsit does not need a var list, it has already been added

2018-05-28 20:50 UTC, TimZ99 commented
I noticed. The review wasn't hidden automatically.

2018-05-28 21:08 UTC, wardpieters commented on src/psm/Txtmsg/Octopush.php
> +					"sms_type" => "XXX", //FR = premium, WWW = world, XXX = Low cost
If premium, you NEED to add 

> STOP au XXXX

to the message, otherwise it does not work. See the API documentation; http://www.octopush-dm.com/public/docs/envoyer-des-sms-avec-octopush.pdf.

2018-05-28 21:15 UTC, TimZ99 commented
If type = FR the message will be: `Test+message+STOP+au+XXXXX`

2018-05-28 21:16 UTC, TimZ99 commented on src/psm/Txtmsg/Octopush.php
> +					"sms_type" => "XXX", //FR = premium, WWW = world, XXX = Low cost
If type = FR the message will be: Test+message+STOP+au+XXXXX

2018-05-28 21:18 UTC, TimZ99 commented
Damm, this pr started small, now it has 43 commits 😂

2018-05-28 21:19 UTC, TimZ99 commented
Can you make a list of all the issues that will be closed on merge?

2018-05-28 21:23 UTC, wardpieters commented
Closes #588, closes #460, closes #586 
Not relevant anymore: closes #223

2018-05-28 22:49 UTC, TimZ99 approved these changes

2018-05-29 12:01 UTC, TimZ99 approved these changes

2018-05-29 12:13 UTC, merged