Added Norwegian language + updated spelling in English language
phpservermon/phpservermon pull request #605
Opened 2018-07-17 19:07 UTC by DanielRTRD

2018-07-24 22:13 UTC, TimZ99 requested changes
Thanks for the translation! No major issues, just a few questions, and some changes.

2018-07-24 22:13 UTC, TimZ99 commented on src/lang/no_NB.lang.php
> + * @author      Pepijn Over <pep@mailbox.org>
Aren't you the author of this file?

2018-07-24 22:13 UTC, TimZ99 commented on src/lang/no_NB.lang.php
> +		'authentication_settings' => 'Autentiseringsinnstillinger (Optional)',
Does 'optional' have a translation?

2018-07-24 22:13 UTC, TimZ99 commented on src/lang/no_NB.lang.php
> +		'settings_sms' => 'tekstmeldinger innstillinger',
tekstmeldinger with a capital letter please

2018-07-24 22:13 UTC, TimZ99 commented on src/lang/no_NB.lang.php
> +		'settings_sms' => 'tekstmeldinger innstillinger',
SMS is used everywhere. Why do you use tekstmeldinger in this case?

2018-07-24 22:13 UTC, TimZ99 commented on src/lang/no_NB.lang.php
> +		'on_pushover_title' => 'Server \'%LABEL%\' is RUNNING',
Forgotten?

2018-07-24 22:13 UTC, TimZ99 commented on src/lang/en_US.lang.php
> +		'sms_sent' => 'Sms sent',
SMS is used everywhere else in this file. What is the reason that this one needs to be changed?

2018-08-09 20:58 UTC, DanielRTRD commented
Fixed the issues :)

2018-08-10 00:41 UTC, TimZ99 commented on src/lang/no_NB.lang.php
> + * @copyright   Copyright (c) 2008-2018 Daniel S. Billing <daniel@infihex.com>
Also the copyright?

2018-08-13 09:43 UTC, DanielRTRD commented
Done 💯

2018-08-13 10:37 UTC, TimZ99 approved these changes

2018-08-13 10:39 UTC, merged

2018-08-13 10:40 UTC, TimZ99 commented
🎉