Add Traditional Chinese Language File.
phpservermon/phpservermon pull request #618
Opened 2018-08-13 07:21 UTC by jasoncheng7115

Support Traditional Chinese.

2018-08-13 10:26 UTC, TimZ99 requested changes
You have 8 removed translations and 37 translations that are missing.
The translation files are based on the most recent English translation (en_US).

2018-08-13 10:26 UTC, TimZ99 commented on src/lang/zh_TW.lang.php
> +		'sms_gateway_mosms' => 'Mosms',
The SMS gateways aren't in the translation files anymore.

2018-08-13 10:27 UTC, TimZ99 commented
Thank you very much for the PR!
You can use [the translation editor](https://github.com/timz99/phpservermon-language-editor) to view the missing translations.

2018-08-13 15:54 UTC, jasoncheng7115 commented
Thanks! I have finished the Translation by using the Translation Editor and will re-submit the PR.

2018-08-13 23:24 UTC, TimZ99 commented
Thanks for the update, there are quite a lot of changes!

Just a few points:
The words: Port, Host, Error and IMPORTANT are not translated.
Same goes for alert_proxy and telegram_bot_username_found.
pushover_error_nokey (key found), telegram_description (documentation) and alert_proxy_url contain some English.
I will stop after this one, I promise 😅: the notifications (online messages) are missing ` it was down for %LAST_OFFLINE_DURATION%:`.

2018-08-13 23:26 UTC, TimZ99 requested changes

2018-08-13 23:26 UTC, TimZ99 commented on src/lang/zh_TW.lang.php
> + * @author      manhere <https://github.com/manhere>
You can put your own name here 😄

2018-08-14 01:19 UTC, jasoncheng7115 commented on src/lang/zh_TW.lang.php
> + * @author      manhere <https://github.com/manhere>
😄 thanks, I've put it on.

2018-08-14 01:24 UTC, jasoncheng7115 commented
I will revise the missing part in your next release. ✌️✌️

2019-12-19 19:05 UTC, TimZ99 commented
Doesn't seem to get an update, so closing the pr. Feel free to reopen.

2019-12-19 19:29 UTC, merged

2019-12-19 19:29 UTC, TimZ99 commented
Thanks for your work. I will merge this part and hopefully new additions will come.