Added catalan ca_ES language translation file
phpservermon/phpservermon pull request #733
Opened 2019-05-17 21:37 UTC by caos30

I only added the file: /src/lang/ca_ES.lang.php
I'm using it on my production server without problems ;-)
Cheers!
Sergi

2019-05-19 00:41 UTC, TimZ99 requested changes
Thanks for the translation!
It needs to be updated to the latest version (develop branch) as there are some 'breaking' changes.

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'yesterday_format' => 'Yesterday at %k:%M',
```suggestion
		'yesterday_format' => 'Ahir a %k:%M',
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'other_day_format' => '%A at %k:%M',
```suggestion
		'other_day_format' => '%A a les %k:%M',
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'server_update' => 'FER PING ARA',
```suggestion
		'server_update' => 'Actualització',
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'log_status' => 'LOG d\'estat',
```suggestion
		'log_status' => 'Log d\'estat',
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'log_status_description' => "Si el LOG d'estat es configura a SÍ, l'aplicació enregistrarà aquells events que disparin les notificacions.",
```suggestion
		'log_status_description' => "Si el log d'estat es configura a SÍ, l'aplicació enregistrarà aquells events que disparin les notificacions.",
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'sms_gateway_mosms' => 'Mosms',
sms_gateway_.... are no longer in use. Please update to latest version. You can use [this](https://github.com/TimZ99/phpservermon-language-editor) tool if you want.

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'log_retention_period' => "Període de retenció al LOG",
```suggestion
		'log_retention_period' => "Període de retenció al log",
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'off_sms' => 'El servidor \'%LABEL%\' NO RESPON: IP=%IP%, Port=%PORT%. Error=%ERROR%',
Notifications have a new variable. Please update to the latest version.

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +	'name' => 'Català',
```suggestion
	'name' => 'Català - Catalán',
```

2019-05-19 00:41 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'update_available' => 'Hi ha disponible una nova versió ({version}) a <a href="http://www.phpservermonitor.org" target="_blank">http://www.phpservermonitor.org</a>.',
URL has been changed. See the latest update.

2019-05-19 06:19 UTC, caos30 commented on src/lang/ca_ES.lang.php
> +		'sms_gateway_mosms' => 'Mosms',
Well, the problem is not my tool used. I realize that my error was to use the master branch as reference. I should take the develop branch. Let me download that develop version and i will do a new commit and pull request.

I apologise by waste your time... i'm very sorry :-(
Thanks anyway for your patient.
Sergi

2019-05-19 06:44 UTC, TimZ99 commented on src/lang/ca_ES.lang.php
> +		'sms_gateway_mosms' => 'Mosms',
No problem at all! It’s worth it 👍

2019-06-18 05:34 UTC, caos30 commented on src/lang/ca_ES.lang.php
> +		'log_retention_period' => "Període de retenció al LOG",
"log" is an english word. So it cannot be used inside another language paragraph without some kind of special mark. It could be using an _italic_ font-style, or "double quoting" it. But because this label translation could be used in unknown circumstances (for example an javascript native alert() function cannot use italic or htmlentities), it's safe to put LOG using capital letters, to differenciate this word from the other catalan words.

It applies to other "foreign" languages (other than english) when inserting english words.

2019-06-18 05:48 UTC, caos30 commented on src/lang/ca_ES.lang.php
> +		'server_update' => 'FER PING ARA',
Believe me, i invested more than 2 hours thinking about the label for this button. "Actualització" (literally means Update as NOUN, not as verb) is not a good translation. 

In fact, this button is special in it behaviour. It does a "ping" (or a "request") to all the defined servers/websites defined in the system. So it is very difficult to find an adequate expression in a single word. If you ask me: "update" is a very bad choose, because it means a lot of different things depending on the context. So in this case, as a "button" in the main menu of the webapp... it says nothing. Even for me that i'm using since sveral months the app, sometimes confus to me this "update" label!!!

So, i really choose the concept of "TO DO A PING NOW" as a very much better expression of the consequences of do click over that button. In catalan, this expression is just very brief: "fer ping ara".

I choosed to put in CAPITAL LETTERS to be able to differenciate the 3 words as a unique "clickable entity". Because if you put it in lowercase then they seem 3 different option menu. If you ask me: this is a bad design of the HTML/CSS of the menu. Take in account that other menu options in some languages can have 2 or more words to express the same that in english only need one. So, i would design that menu taking this in account.

2019-06-18 05:50 UTC, caos30 commented on src/lang/ca_ES.lang.php
> +		'log_status' => 'LOG d\'estat',
As i commented in other comment of this pull request, it's necessary to put LOG in CAPITAL LETTERS because is a FOREIGN WORD (english) in a catalan phrase, and it's necessary to differentiate or mark it in some way. Uppercase it's a great and simple way. Just like you write USA, although the correct way would be U.S.A.

2019-09-17 14:29 UTC, TimZ99 approved these changes

2019-09-17 14:36 UTC, merged

2019-09-17 14:36 UTC, TimZ99 commented
Great work!

2019-09-17 18:55 UTC, caos30 commented
Thanks to you Tim. It's really a great opensource project. I use it to monitor all my websites.

In fact, i have done a DARK THEME ;-) see... the image below. But i'm waiting for to have a little of time to put it "choosable" for the user. I mean... now i only have made a rude hacking of the original theme. I want to add to the interface at least an icon to toggle between light/dark theme ;-)

Do you think that this feature can be included in the main project if i develop it?

Best regards!

![web-monitor-dark-theme](https://user-images.githubusercontent.com/1767547/65070492-9193e080-d941-11e9-8350-b193a0ab06fd.png)