Issue #734
phpservermon/phpservermon pull request #741
Opened 2019-06-05 23:30 UTC by dktcoding

Truncate the outputs if necessary, then show a `See complete...` button and show the outputs on a modal:

![Screenshot from 2019-06-05 20-22-14](https://user-images.githubusercontent.com/709639/58996946-b029fd80-87d0-11e9-8c53-07c85e95a958.png)

![Screenshot from 2019-06-05 20-22-51](https://user-images.githubusercontent.com/709639/58996948-b15b2a80-87d0-11e9-9bcb-35af5518e59a.png)

2019-06-05 23:34 UTC, dktcoding commented
Full disclosure... this is my first time with Twig, so there's probably a better solution (this one is fully functional though).

2019-07-17 17:00 UTC, TimZ99 requested changes

2019-07-17 17:00 UTC, TimZ99 commented on src/templates/default/module/server/server/view.tpl.html
> +								See complete...
Maybe 'show more' suits better?

2019-07-17 17:00 UTC, TimZ99 commented on src/templates/default/module/server/server/view.tpl.html
> +				<div class="modal-body" style="word-wrap: break-word;font-family: Mono">
Why the font-family: Mono?

2019-09-17 11:04 UTC, TimZ99 approved these changes

2019-09-17 11:06 UTC, merged